<?php

return [
    'OnBeforeCommentSave' => [],
    'OnCommentSave' => [],
    'OnBeforeCommentPublish' => [],
    'OnCommentPublish' => [],
    'OnBeforeCommentUnpublish' => [],
    'OnCommentUnpublish' => [],
    'OnBeforeCommentDelete' => [],
    'OnCommentDelete' => [],
    'OnBeforeCommentUndelete' => [],
    'OnCommentUndelete' => [],
    'OnBeforeCommentRemove' => [],
    'OnCommentRemove' => [],
    'OnBeforeTicketThreadClose' => [],
    'OnTicketThreadClose' => [],
    'OnBeforeTicketThreadOpen' => [],
    'OnTicketThreadOpen' => [],
    'OnBeforeTicketThreadDelete' => [],
    'OnTicketThreadDelete' => [],
    'OnBeforeTicketThreadUndelete' => [],
    'OnTicketThreadUndelete' => [],
    'OnBeforeTicketThreadRemove' => [],
    'OnTicketThreadRemove' => [],
    'OnBeforeTicketVote' => [],
    'OnTicketVote' => [],
    'OnBeforeCommentVote' => [],
    'OnCommentVote' => [],
    'OnBeforeTicketStar' => [],
    'OnTicketStar' => [],
    'OnBeforeTicketUnStar' => [],
    'OnTicketUnStar' => [],
    'OnBeforeCommentStar' => [],
    'OnCommentStar' => [],
    'OnBeforeCommentUnStar' => [],
    'OnCommentUnStar' => [],
]; 